name: twitter
channels:
- defaults
dependencies:
- Python=3.6.1
- numpy=1.12.1
- pandas=0.20.1
- seaborn=0.7.1
- re=2.2.1
- nltk=3.2.3
- beautifulsoup4=4.6.0
- matplotlib=2.1.1
- sortedcollections=0.5.3
- scikit-learn=0.19.1
- scikit-image=0.13.0
- scipy=1.0.0
- statsmodels=0.8.0
- pip:
  - gensim==3.2.0
  - jmespath==0.9.3
  - joblib==0.11
  - prompt-toolkit==1.0.15
  - pyldavis==2.1.1
  - ruamel-yaml==0.11.14
  - s3transfer==0.1.12
  - smart-open==1.5.5
  - stop-words==2015.2.23.1
  - tables==3.4.2
  - wordcloud==1.3.2
